name: CI – Lint, Test, and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: digit-classification
  REGISTRY: docker.io
  DOCKERHUB_USER: your-dockerhub-username

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:test .

    - name: Run pre-commit
      run: docker run --rm $IMAGE_NAME:test poetry run pre-commit run --all-files

    - name: Run pytest
      run: docker run --rm $IMAGE_NAME:test poetry run pytest

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image to Docker Hub
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        TAG=${{ env.REGISTRY }}/${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:latest
        docker tag $IMAGE_NAME:test $TAG
        docker push $TAG
